seed: 42

data:
  data_name: Cora
  data_class: Planetoid
  batch_size: 64
  num_workers: 4

model:
  name: gcn
  hidden_dim: 32
  dropout: 0.8

train:
  epochs: 200
  lr: 0.01
  weight_decay: 0.0005
  device: cuda